services:
  mongo:
    image: mongo:7
    container_name: logistock_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Persistencia de datos
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js # Seed automático
    environment:
      - MONGO_INITDB_DATABASE=cac_valleverde
    restart: always

  web:
    build: .
    container_name: logistock_app
    ports:
      - "8501:8501"
    # Pasamos las variables de entorno al contenedor
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_URL=mongodb://mongo:27017/
      - DB_NAME=cac_valleverde
    depends_on:
      - mongo
    restart: always

volumes:
  mongo_data: # Volumen persistente para no perder datos entre reinicios
