version: '3.8'

services:
  web:
    build: .
    container_name: logistock_cacao_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
